const {test,expect}=require('@playwright/test');
test.afterEach(async({page})=>{const targets=await page.locator('button:visible').evaluateAll(buttons=>buttons.map(b=>({text:b.textContent.trim(),height:b.getBoundingClientRect().height})));for(const target of targets)expect(target.height,`Touch height: ${target.text}`).toBeGreaterThanOrEqual(44);});
test.beforeEach(async({page})=>{await page.addInitScript(()=>{let s={lists:[{id:'default',name:'내 다운로드'}],tasks:[],theme:'system'};window.__qaState=s;window.__commands=[];window.Android={state:()=>JSON.stringify(s),shared:()=>'',command:text=>{const c=JSON.parse(text);window.__commands.push(c);if(c.action==='addList'){let id='l'+s.lists.length;s.lists.push({id,name:c.name});return JSON.stringify({id})}if(c.action==='add'){let urls=[...new Set(c.text.match(/https?:\/\/[^\s]+/g)||[])],added=0,duplicate=0;for(const url of urls){if(s.tasks.some(t=>t.url===url&&t.list===c.list)){duplicate++;continue;}s.tasks.push({id:'t'+s.tasks.length,title:'매우 긴 한글 영상 제목 · 원본 내용과 장면을 확인하기 위한 다운로드 테스트',url,list:c.list,status:'ready',format:c.format||'mp4',quality:c.quality||'best',playlist:!!c.playlist,message:'다운로드 준비',progress:0});added++}return JSON.stringify({added,duplicate})}if(c.action==='theme')s.theme=c.value;if(c.action==='enqueue')s.tasks.forEach(t=>{if((c.ids||[c.id]).includes(t.id))t.status='queued'});if(c.action==='move')s.tasks.forEach(t=>{if(c.ids.includes(t.id))t.list=c.list});if(c.action==='deleteFiles')s.tasks.forEach(t=>{if((c.ids||[c.id]).includes(t.id)){t.files=[];t.status='ready';t.message='저장 파일 삭제됨';}});if(c.action==='remove')s.tasks=s.tasks.filter(t=>!(c.ids||[c.id]).includes(t.id));return '{}';}};});await page.goto('/');});
test('named lists, link entry, duplicate, search, filters, moving and removal',async({page},info)=>{await page.getByRole('button',{name:'＋ 새 목록'}).click();await page.locator('#listName').fill('참고 영상 · 사용자 QA');await page.locator('#saveList').click();await expect(page.getByRole('heading',{name:'참고 영상 · 사용자 QA'})).toBeVisible();await page.locator('#addTop').click();await page.locator('#linksInput').fill('https://example.org/one.mp4\nhttps://example.org/two.m3u8');await page.locator('#saveLinks').click();await expect(page.locator('.card')).toHaveCount(2);await page.locator('#addTop').click();await page.locator('#linksInput').fill('https://example.org/one.mp4');await page.locator('#saveLinks').click();await expect(page.locator('.card')).toHaveCount(2);await expect(page.locator('#toast')).toContainText('중복 1개');await page.locator('#search').fill('two');await expect(page.locator('.card')).toHaveCount(1);await page.locator('#search').fill('');await page.getByRole('button',{name:'모두 선택'}).click();await expect(page.locator('#selectBar')).toBeVisible();await page.locator('#selMove').click();await page.locator('#moveList').selectOption('default');await page.locator('#moveNow').click();await expect(page.locator('.card')).toHaveCount(0);await page.getByRole('button',{name:'내 다운로드 2',exact:true}).click();await expect(page.locator('.card')).toHaveCount(2);await page.locator('[data-filter=failed]').click();await expect(page.getByRole('heading',{name:'조건에 맞는 영상이 없어요'})).toBeVisible();await page.locator('[data-filter=all]').click();await page.screenshot({path:`screenshots/${info.project.name}-list.png`,fullPage:true});await page.getByRole('button',{name:'모두 선택'}).click();await page.locator('#selRemove').click();await page.locator('#deleteEntries').click();await expect(page.locator('.card')).toHaveCount(0);});
test('theme, invalid links, dialog back, long text and no horizontal overflow',async({page},info)=>{await page.locator('#addTop').click();await page.locator('#linksInput').fill('주소 아님');await expect(page.locator('#saveLinks')).toBeDisabled();await page.locator('#linksInput').fill('https://example.org/'+ 'a'.repeat(230));await page.locator('#saveLinks').click();await page.locator('[data-nav=settings]').click();await page.locator('#theme').selectOption('dark');await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.screenshot({path:`screenshots/${info.project.name}-settings.png`,fullPage:true});await page.locator('#theme').selectOption('light');await page.locator('[data-nav=lists]').click();await expect(page.locator('.card')).toHaveCount(1);const geometry=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,nav:[...document.querySelectorAll('nav button')].map(b=>b.getBoundingClientRect().height)}));expect(geometry.scroll).toBeLessThanOrEqual(geometry.width);expect(Math.min(...geometry.nav)).toBeGreaterThanOrEqual(44);await page.locator('.detail').click();await expect(page.locator('#modal')).toBeVisible();expect(await page.evaluate(()=>handleBack())).toBe(true);await expect(page.locator('#modal')).not.toBeVisible();});

test('open page from link input without creating an entry; automatic defaults',async({page},info)=>{
 await page.locator('#addTop').click();await page.locator('#linksInput').fill('https://example.org/watch/one');
 await expect(page.locator('#format')).toHaveCount(0);await expect(page.locator('#quality')).toHaveCount(0);
 await page.screenshot({path:`screenshots/${info.project.name}-add.png`,fullPage:true});
 await page.locator('#browseInput').click();await expect(page.locator('#modal')).not.toBeVisible();
 const commands=await page.evaluate(()=>window.__commands);expect(commands.at(-1)).toMatchObject({action:'browser',url:'https://example.org/watch/one',list:'default'});
 await expect(page.locator('.card')).toHaveCount(0);
 await page.locator('#addTop').click();await page.locator('#linksInput').fill('https://example.org/watch/one');await page.locator('#saveLinks').click();
 expect(await page.evaluate(()=>window.__commands.find(c=>c.action==='add'))).toMatchObject({format:'mp4',quality:'best'});
 await page.getByRole('button',{name:'페이지 열기',exact:true}).last().click();expect(await page.evaluate(()=>window.__commands.at(-1).action)).toBe('browser');
 await page.locator('#quickBrowse').click();await page.locator('#browseUrl').fill('example.org');await page.locator('#browseGo').click();expect(await page.evaluate(()=>window.__commands.at(-1).url)).toBe('https://example.org');
});
test('saved-file deletion retains link and requires explicit confirmation',async({page},info)=>{
 await page.evaluate(()=>{window.__qaState.tasks.push({id:'file',list:'default',url:'https://example.org/video',title:'저장된 영상',status:'completed',format:'mp4',quality:'best',files:[{uri:'content://media/external/downloads/7',name:'영상.mp4',bytes:2048}]});refresh(true);});
 await page.locator('.detail').click();await page.locator('#removeTask').click();await expect(page.locator('#deleteEntries')).toBeEnabled();await expect(page.locator('#deleteSaved')).toBeEnabled();
 await page.screenshot({path:`screenshots/${info.project.name}-delete.png`,fullPage:true});
 await page.locator('#deleteSaved').click();await page.locator('#no').click();expect(await page.evaluate(()=>window.__qaState.tasks[0].files.length)).toBe(1);
 await page.locator('.detail').click();await page.locator('#removeTask').click();await page.locator('#deleteSaved').click();await page.locator('#yes').click();
 await expect(page.locator('.card')).toHaveCount(1);expect(await page.evaluate(()=>window.__qaState.tasks[0])).toMatchObject({status:'ready',files:[]});
 expect(await page.evaluate(()=>window.__commands.at(-1))).toMatchObject({action:'deleteFiles',ids:['file']});
});
test('busy entries cannot be deleted; existing link can start from entry form',async({page})=>{
 await page.locator('#addTop').click();await page.locator('#linksInput').fill('https://example.org/one.mp4');await page.locator('#saveLinks').click();
 await page.locator('#addTop').click();await page.locator('#linksInput').fill('https://example.org/one.mp4');await page.locator('#downloadLinks').click();
 await expect(page.locator('.card')).toHaveCount(1);expect(await page.evaluate(()=>window.__qaState.tasks[0].status)).toBe('queued');
 await page.locator('.selectTask').click();await page.locator('#selRemove').click();await expect(page.locator('#deleteEntries')).toBeDisabled();await expect(page.locator('#deleteSaved')).toBeDisabled();await page.locator('#closeDialog').click();
 await page.locator('#selClose').click();
});
test('long titles, enlarged text, keyboard-size dialog and reduced motion',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#addTop').click();await page.locator('#linksInput').fill('https://example.org/'+ 'long'.repeat(70));
 await page.setViewportSize({width:360,height:480});await expect(page.locator('#downloadLinks')).toBeVisible();await page.locator('#downloadLinks').scrollIntoViewIfNeeded();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.locator('#saveLinks').click();await page.evaluate(()=>{document.body.style.fontSize='20px';});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await expect(page.getByText('MP4 우선')).toHaveCount(0);await expect(page.getByText('최고 화질')).toHaveCount(0);
});
