package kr.co.kjw.videodownloader;

import android.app.*;
import android.os.*;
import android.view.*;
import android.webkit.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

public class BrowserActivity extends Activity {
    private WebView web;
    private EditText address;
    private Button media;
    private final LinkedHashMap<String,String> candidates=new LinkedHashMap<>();
    private volatile String page="";
    private final Handler timer=new Handler(Looper.getMainLooper());
    private final Runnable poll=new Runnable(){public void run(){collect();timer.postDelayed(this,1800);}};
    private static final String COLLECT="(function(){const a=[];const ok=u=>typeof u==='string'&&/^https?:/.test(u);document.querySelectorAll('video,audio,source').forEach(v=>{[v.currentSrc,v.src,v.getAttribute('data-src')].forEach(u=>{if(ok(u))a.push(u)})});performance.getEntriesByType('resource').forEach(r=>{if(/\\.(m3u8|mpd|mp4|webm|m4a|mp3)(\\?|$)/i.test(r.name))a.push(r.name)});(window.__vdMedia||[]).forEach(u=>a.push(u));return JSON.stringify({title:document.title,urls:[...new Set(a)].slice(0,100)});})()";
    private static final String HOOK="(function(){if(window.__vdHook)return;window.__vdHook=true;window.__vdMedia=[];let add=(u,t)=>{if(/^(video|audio)\\//i.test(t||'')||/mpegurl|dash\\+xml/i.test(t||''))window.__vdMedia.push(u)};let old=window.fetch;if(old)window.fetch=function(){return old.apply(this,arguments).then(r=>{add(r.url,r.headers.get('content-type'));return r})};let x=XMLHttpRequest.prototype.open;XMLHttpRequest.prototype.open=function(){this.addEventListener('load',()=>add(this.responseURL,this.getResponseHeader('Content-Type')));return x.apply(this,arguments)};})()";
    @Override public void onCreate(Bundle state){super.onCreate(state);Store.init(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(12,12,12,8);root.setBackgroundColor(0xfff7f8fc);LinearLayout top=new LinearLayout(this);Button back=new Button(this);back.setText("닫기");back.setOnClickListener(v->finish());top.addView(back,new LinearLayout.LayoutParams(dp(64),-2));address=new EditText(this);address.setSingleLine(true);address.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_URI);address.setText(getIntent().getStringExtra("url"));top.addView(address,new LinearLayout.LayoutParams(0,-2,1));Button go=new Button(this);go.setText("이동");go.setOnClickListener(v->navigate());top.addView(go,new LinearLayout.LayoutParams(dp(64),-2));root.addView(top);TextView hint=new TextView(this);hint.setText("페이지에서 영상을 재생하면 저장 가능한 미디어를 찾습니다.");hint.setTextColor(0xff4b5563);hint.setPadding(0,8,0,8);root.addView(hint);web=new WebView(this);web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.getSettings().setMediaPlaybackRequiresUserGesture(true);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.getSettings().setMixedContentMode(WebSettings.MIXED_CONTENT_COMPATIBILITY_MODE);CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(web,true);
        // No privileged JavaScript bridge is exposed to website content.
        web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return !LinkParser.valid(r.getUrl().toString());}@Override public void onPageStarted(WebView v,String url,android.graphics.Bitmap icon){page=url;address.setText(url);}@Override public void onPageFinished(WebView v,String url){page=url;web.evaluateJavascript(HOOK,null);collect();}@Override public void onPageCommitVisible(WebView v,String url){web.evaluateJavascript(HOOK,null);}@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){String url=r.getUrl().toString();if(url.matches("(?i).*\\.(m3u8|mpd|mp4|webm|mov|mkv|mp3|m4a|aac|ogg|wav|flac)([?].*)?$"))add(url,page);return null;}});
        web.setDownloadListener((url,agent,disposition,mime,length)->{if(mime!=null&&(mime.startsWith("video/")||mime.startsWith("audio/")||mime.contains("mpegurl")||mime.contains("dash")))add(url,page);});root.addView(web,new LinearLayout.LayoutParams(-1,0,1));LinearLayout bottom=new LinearLayout(this);media=new Button(this);media.setText("찾은 미디어 0개");media.setOnClickListener(v->{collect(true);});bottom.addView(media,new LinearLayout.LayoutParams(0,-2,1));Button reset=new Button(this);reset.setText("로그인 지우기");reset.setOnClickListener(v->new AlertDialog.Builder(this).setMessage("앱 브라우저의 로그인 정보를 지울까요?").setNegativeButton("취소",null).setPositiveButton("지우기",(d,w)->{CookieManager.getInstance().removeAllCookies(null);CookieManager.getInstance().flush();android.webkit.WebStorage.getInstance().deleteAllData();toast("로그인 정보를 지웠습니다.");}).show());bottom.addView(reset);root.addView(bottom);Button retry=new Button(this);retry.setText("원래 주소 재시도");retry.setOnClickListener(v->retryOriginal());root.addView(retry);setContentView(root);root.setOnApplyWindowInsetsListener((v,insets)->{if(Build.VERSION.SDK_INT>=30){android.graphics.Insets b=insets.getInsets(WindowInsets.Type.systemBars());android.graphics.Insets k=insets.getInsets(WindowInsets.Type.ime());v.setPadding(12+b.left,12+b.top,12+b.right,8+Math.max(b.bottom,k.bottom));}else v.setPadding(12+insets.getSystemWindowInsetLeft(),12+insets.getSystemWindowInsetTop(),12+insets.getSystemWindowInsetRight(),8+insets.getSystemWindowInsetBottom());return insets;});navigate();timer.postDelayed(poll,1800);}
    private void navigate(){String url=address.getText().toString().trim();if(!LinkParser.valid(url)){toast("http:// 또는 https:// 주소를 입력해 주세요.");return;}synchronized(candidates){candidates.clear();}media.setText("찾은 미디어 0개");page=url;web.loadUrl(url);}
    private void add(String url,String ref){if(!LinkParser.valid(url))return;synchronized(candidates){if(candidates.size()<100)candidates.putIfAbsent(url,ref);}runOnUiThread(()->{if(!isFinishing()&&!isDestroyed())media.setText("찾은 미디어 "+candidates.size()+"개");});}
    private void collect(){collect(false);} private void collect(boolean show){if(web==null||isFinishing())return;web.evaluateJavascript(COLLECT,value->{try{String decoded=(String)new JSONTokener(value).nextValue();JSONObject o=new JSONObject(decoded);JSONArray urls=o.getJSONArray("urls");for(int i=0;i<urls.length();i++)add(urls.optString(i),page);if(show)showMedia();}catch(Exception ignored){}});}
    private void showMedia(){ArrayList<String> urls,refs;synchronized(candidates){urls=new ArrayList<>(candidates.keySet());refs=new ArrayList<>(candidates.values());}if(urls.isEmpty()){toast("영상 재생 후 다시 눌러 주세요. DRM 영상은 저장할 수 없습니다.");return;}String[] labels=new String[urls.size()];for(int i=0;i<urls.size();i++){String u=urls.get(i);String type=u.contains("m3u8")?"HLS 스트림":u.contains("mpd")?"DASH 스트림":"미디어 파일";try{labels[i]=type+" · "+LinkParser.host(u)+"\n"+new URI(u).getPath();}catch(Exception e){labels[i]=type;}}new AlertDialog.Builder(this).setTitle("저장할 미디어 선택").setItems(labels,(d,n)->addSelected(urls.get(n),refs.get(n))).setNegativeButton("닫기",null).show();}
    private void addSelected(String url,String ref){try{File dir=new File(getFilesDir(),"cookies");dir.mkdirs();File jar=new File(dir,UUID.randomUUID()+".txt");StringBuilder s=new StringBuilder("# Netscape HTTP Cookie File\n");LinkedHashSet<String> origins=new LinkedHashSet<>(Arrays.asList(url,ref));for(String origin:origins){if(!LinkParser.valid(origin))continue;String host=LinkParser.host(origin);String cookies=CookieManager.getInstance().getCookie(origin);if(cookies==null)continue;for(String part:cookies.split(";")){int eq=part.indexOf('=');if(eq<1)continue;String name=part.substring(0,eq).trim(),val=part.substring(eq+1).trim();if(name.matches(".*[\\r\\n\\t].*")||val.matches(".*[\\r\\n\\t].*"))continue;s.append(host).append("\tFALSE\t/\t").append(origin.startsWith("https")?"TRUE":"FALSE").append("\t0\t").append(name).append('\t').append(val).append('\n');}}try(FileOutputStream out=new FileOutputStream(jar)){out.write(s.toString().getBytes(StandardCharsets.UTF_8));}String title=web.getTitle()==null?LinkParser.host(url):web.getTitle();JSONObject result=Store.command(Store.obj("action","add","text",url,"title",title,"list",getIntent().getStringExtra("list"),"referer",ref,"cookieFile",jar.getAbsolutePath(),"userAgent",web.getSettings().getUserAgentString()));if(result.optInt("added")<1)jar.delete();toast(result.optInt("added")>0?"목록에 추가했습니다. 앱으로 돌아가 다운로드를 시작하세요.":"이미 목록에 있는 주소입니다.");}catch(Exception e){toast("미디어를 추가하지 못했습니다.");}}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    private int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
    private File cookieJar(String url,String ref)throws Exception{File dir=new File(getFilesDir(),"cookies");dir.mkdirs();File file=new File(dir,UUID.randomUUID()+".txt");StringBuilder s=new StringBuilder("# Netscape HTTP Cookie File\n");LinkedHashSet<String> urls=new LinkedHashSet<>(Arrays.asList(url,ref));for(String origin:urls){if(!LinkParser.valid(origin))continue;String cookies=CookieManager.getInstance().getCookie(origin);if(cookies==null)continue;for(String part:cookies.split(";")){int eq=part.indexOf('=');if(eq<1)continue;String key=part.substring(0,eq).trim(),val=part.substring(eq+1).trim();if(key.matches(".*[\\r\\n\\t].*")||val.matches(".*[\\r\\n\\t].*"))continue;s.append(LinkParser.host(origin)).append("\tFALSE\t/\t").append(origin.startsWith("https")?"TRUE":"FALSE").append("\t0\t").append(key).append('\t').append(val).append('\n');}}try(FileOutputStream out=new FileOutputStream(file)){out.write(s.toString().getBytes(StandardCharsets.UTF_8));}return file;}
    private void retryOriginal(){String id=getIntent().getStringExtra("taskId"),original=getIntent().getStringExtra("url");try{JSONObject t=id==null?null:Store.task(id);if(t!=null&&Arrays.asList("queued","analyzing","downloading","exporting","pausing","completed").contains(t.optString("status"))){toast("진행 중이거나 완료한 항목입니다.");return;}File jar=cookieJar(original,page);if(t!=null){Store.patch(id,Store.obj("cookieFile",jar.getAbsolutePath(),"referer",page,"userAgent",web.getSettings().getUserAgentString()));Store.command(Store.obj("action","enqueue","id",id));startForegroundService(new android.content.Intent(this,DownloadService.class));toast("로그인 정보로 원래 주소를 재시도합니다.");finish();}else{JSONObject r=Store.command(Store.obj("action","add","text",original,"list",getIntent().getStringExtra("list"),"cookieFile",jar.getAbsolutePath(),"referer",page,"userAgent",web.getSettings().getUserAgentString()));if(r.optInt("added")==0)jar.delete();toast("목록에서 다운로드를 시작해 주세요.");}}catch(Exception e){toast("재시도를 준비하지 못했습니다.");}}
    @Override public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();}
    @Override protected void onDestroy(){timer.removeCallbacksAndMessages(null);if(web!=null){web.stopLoading();web.destroy();web=null;}super.onDestroy();}
}
