package kr.co.kjw.videodownloader;

import android.app.*;
import android.os.*;
import android.view.*;
import android.webkit.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

public class BrowserActivity extends Activity {
    private WebView web;
    private EditText address;
    private Button media;
    private final LinkedHashMap<String,String> candidates=new LinkedHashMap<>();
    private volatile String page="";
    private final Handler timer=new Handler(Looper.getMainLooper());
    private final Runnable poll=new Runnable(){public void run(){collect();timer.postDelayed(this,1800);}};
    private static final String COLLECT="(function(){const a=[];const ok=u=>typeof u==='string'&&/^https?:/.test(u);document.querySelectorAll('video,audio,source').forEach(v=>{[v.currentSrc,v.src,v.getAttribute('data-src')].forEach(u=>{if(ok(u))a.push(u)})});performance.getEntriesByType('resource').forEach(r=>{if(/\\.(m3u8|mpd|mp4|webm|m4a|mp3)(\\?|$)/i.test(r.name))a.push(r.name)});(window.__vdMedia||[]).forEach(u=>a.push(u));return JSON.stringify({title:document.title,urls:[...new Set(a)].slice(0,100)});})()";
    private static final String HOOK="(function(){if(window.__vdHook)return;window.__vdHook=true;window.__vdMedia=[];let add=(u,t)=>{if(/^(video|audio)\\//i.test(t||'')||/mpegurl|dash\\+xml/i.test(t||''))window.__vdMedia.push(u)};let old=window.fetch;if(old)window.fetch=function(){return old.apply(this,arguments).then(r=>{add(r.url,r.headers.get('content-type'));return r})};let x=XMLHttpRequest.prototype.open;XMLHttpRequest.prototype.open=function(){this.addEventListener('load',()=>add(this.responseURL,this.getResponseHeader('Content-Type')));return x.apply(this,arguments)};})()";
    private Button back,forward;
    private TextView status;
    private ProgressBar progress;
    private int surface,ink,muted,line,background,brand,primaryInk;
    @Override public void onCreate(Bundle state){
        super.onCreate(state);Store.init(this);
        String theme=Store.state().optString("theme","system");boolean dark="dark".equals(theme)||("system".equals(theme)&&(getResources().getConfiguration().uiMode&android.content.res.Configuration.UI_MODE_NIGHT_MASK)==android.content.res.Configuration.UI_MODE_NIGHT_YES);
        background=dark?0xff10191c:0xfff6f7f9;surface=dark?0xff19262a:0xffffffff;ink=dark?0xffedf6f4:0xff16232b;muted=dark?0xffa4b7bc:0xff596971;line=dark?0xff304349:0xffdce4e6;brand=dark?0xff84d5c2:0xff07665d;primaryInk=dark?0xff102823:0xffffffff;
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(background);
        LinearLayout chrome=new LinearLayout(this);chrome.setOrientation(LinearLayout.VERTICAL);chrome.setPadding(dp(16),dp(8),dp(16),dp(8));
        LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);Button close=button("닫기",false);close.setOnClickListener(v->finish());header.addView(close,new LinearLayout.LayoutParams(dp(64),dp(48)));
        TextView title=new TextView(this);title.setText("웹에서 찾기");title.setTextColor(ink);title.setTextSize(18);title.setTypeface(null,android.graphics.Typeface.BOLD);title.setGravity(Gravity.CENTER);header.addView(title,new LinearLayout.LayoutParams(0,dp(48),1));
        Button more=button("더보기",false);more.setOnClickListener(v->showMenu(v));header.addView(more,new LinearLayout.LayoutParams(dp(72),dp(48)));chrome.addView(header);
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);address=new EditText(this);address.setSingleLine(true);address.setTextSize(14);address.setTextColor(ink);address.setHintTextColor(muted);address.setHint("웹 주소 입력");address.setPadding(dp(12),0,dp(12),0);address.setBackground(shape(surface,true));address.setSelectAllOnFocus(true);address.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_URI);address.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_GO);address.setOnEditorActionListener((v,action,event)->{if(action==android.view.inputmethod.EditorInfo.IME_ACTION_GO){navigate();return true;}return false;});address.setText(getIntent().getStringExtra("url"));top.addView(address,new LinearLayout.LayoutParams(0,dp(48),1));
        Button go=button("이동",true);go.setOnClickListener(v->navigate());LinearLayout.LayoutParams goParams=new LinearLayout.LayoutParams(dp(64),dp(48));goParams.leftMargin=dp(8);top.addView(go,goParams);chrome.addView(top);
        status=new TextView(this);status.setText("영상을 재생하면 저장할 미디어를 찾습니다.");status.setTextColor(muted);status.setTextSize(12);status.setPadding(dp(2),dp(10),0,dp(2));chrome.addView(status);root.addView(chrome);
        progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);progress.setProgressTintList(android.content.res.ColorStateList.valueOf(brand));root.addView(progress,new LinearLayout.LayoutParams(-1,dp(2)));progress.setVisibility(View.INVISIBLE);
        web=new WebView(this);web.setBackgroundColor(0xffffffff);web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.getSettings().setMediaPlaybackRequiresUserGesture(true);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.getSettings().setMixedContentMode(WebSettings.MIXED_CONTENT_COMPATIBILITY_MODE);CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(web,true);
        // No privileged JavaScript bridge is exposed to website content.
        web.setWebChromeClient(new WebChromeClient(){@Override public void onProgressChanged(WebView view,int value){progress.setProgress(value);progress.setVisibility(value<100?View.VISIBLE:View.INVISIBLE);}});
        web.setWebViewClient(new WebViewClient(){
            @Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest request){return !LinkParser.valid(request.getUrl().toString());}
            @Override public void onPageStarted(WebView view,String url,android.graphics.Bitmap icon){page=url;address.clearFocus();address.setText(url);synchronized(candidates){candidates.clear();}updateMedia();updateNavigation();status.setText("페이지를 여는 중…");}
            @Override public void onPageFinished(WebView view,String url){page=url;web.evaluateJavascript(HOOK,null);collect();updateNavigation();status.setText("영상을 재생한 뒤 미디어 찾기를 눌러 주세요.");}
            @Override public void onPageCommitVisible(WebView view,String url){web.evaluateJavascript(HOOK,null);}
            @Override public void onReceivedError(WebView view,WebResourceRequest request,WebResourceError error){if(request.isForMainFrame())status.setText("페이지를 열지 못했습니다. 주소와 연결을 확인해 주세요.");}
            @Override public WebResourceResponse shouldInterceptRequest(WebView view,WebResourceRequest request){String url=request.getUrl().toString();if(url.matches("(?i).*\\.(m3u8|mpd|mp4|webm|mov|mkv|mp3|m4a|aac|ogg|wav|flac)([?].*)?$"))add(url,page);return null;}
        });
        web.setDownloadListener((url,agent,disposition,mime,length)->{if(mime!=null&&(mime.startsWith("video/")||mime.startsWith("audio/")||mime.contains("mpegurl")||mime.contains("dash")))add(url,page);});root.addView(web,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout footer=new LinearLayout(this);footer.setOrientation(LinearLayout.VERTICAL);footer.setPadding(dp(16),dp(8),dp(16),dp(10));footer.setBackgroundColor(surface);
        LinearLayout navigation=new LinearLayout(this);back=button("뒤로",false);back.setOnClickListener(v->{if(web.canGoBack())web.goBack();});navigation.addView(back,new LinearLayout.LayoutParams(0,dp(48),1));forward=button("앞으로",false);forward.setOnClickListener(v->{if(web.canGoForward())web.goForward();});navigation.addView(forward,new LinearLayout.LayoutParams(0,dp(48),1));Button reload=button("새로고침",false);reload.setOnClickListener(v->web.reload());navigation.addView(reload,new LinearLayout.LayoutParams(0,dp(48),1));footer.addView(navigation);
        LinearLayout actions=new LinearLayout(this);Button save=button("페이지 추가",false);save.setBackground(shape(background,true));save.setOnClickListener(v->savePage());actions.addView(save,new LinearLayout.LayoutParams(0,dp(52),1));media=button("미디어 찾기",true);media.setOnClickListener(v->collect(true));LinearLayout.LayoutParams mediaParams=new LinearLayout.LayoutParams(0,dp(52),1);mediaParams.leftMargin=dp(8);actions.addView(media,mediaParams);footer.addView(actions);root.addView(footer);
        setContentView(root);root.setOnApplyWindowInsetsListener((v,insets)->{if(Build.VERSION.SDK_INT>=30){android.graphics.Insets bars=insets.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout());android.graphics.Insets keyboard=insets.getInsets(WindowInsets.Type.ime());v.setPadding(bars.left,bars.top,bars.right,Math.max(bars.bottom,keyboard.bottom));return WindowInsets.CONSUMED;}v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets.consumeSystemWindowInsets();});root.requestApplyInsets();
        if(Build.VERSION.SDK_INT>=30){WindowInsetsController controller=getWindow().getDecorView().getWindowInsetsController();if(controller!=null)controller.setSystemBarsAppearance(dark?0:WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS,WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS);}else getWindow().getDecorView().setSystemUiVisibility(dark?0:View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);
        if(state!=null){web.restoreState(state);page=web.getUrl()==null?"":web.getUrl();address.setText(page);}else navigate();timer.postDelayed(poll,1800);root.setAlpha(0);root.animate().alpha(1).setDuration(180).start();
    }
    private Button button(String label,boolean primary){Button button=new Button(this);button.setText(label);button.setTextSize(13);button.setAllCaps(false);button.setTextColor(primary?primaryInk:ink);button.setMinWidth(0);button.setMinimumWidth(0);button.setPadding(dp(4),0,dp(4),0);button.setBackground(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(primary?0x33ffffff:0x1807665d),shape(primary?brand:0x00000000,false),null));return button;}
    private android.graphics.drawable.GradientDrawable shape(int color,boolean border){android.graphics.drawable.GradientDrawable drawable=new android.graphics.drawable.GradientDrawable();drawable.setColor(color);drawable.setCornerRadius(dp(12));if(border)drawable.setStroke(dp(1),line);return drawable;}
    private void updateNavigation(){if(back!=null){back.setEnabled(web.canGoBack());back.setAlpha(back.isEnabled()?1f:.38f);forward.setEnabled(web.canGoForward());forward.setAlpha(forward.isEnabled()?1f:.38f);}}
    private void updateMedia(){int count;synchronized(candidates){count=candidates.size();}if(media!=null)media.setText(count==0?"미디어 찾기":"미디어 "+count+"개 보기");}
    private void showMenu(View anchor){PopupMenu menu=new PopupMenu(this,anchor);menu.getMenu().add(0,1,0,"외부 브라우저에서 열기");String id=getIntent().getStringExtra("taskId");if(id!=null&&!id.isEmpty())menu.getMenu().add(0,2,1,"로그인 정보로 다시 받기");menu.getMenu().add(0,3,2,"로그인 정보 초기화");menu.setOnMenuItemClickListener(item->{if(item.getItemId()==1){try{startActivity(new android.content.Intent(android.content.Intent.ACTION_VIEW,android.net.Uri.parse(page)));}catch(Exception e){toast("브라우저를 열 수 없습니다.");}}else if(item.getItemId()==2)retryOriginal();else new AlertDialog.Builder(this).setTitle("로그인 정보 초기화").setMessage("앱 브라우저의 로그인 정보와 사이트 저장 데이터를 지울까요?").setNegativeButton("취소",null).setPositiveButton("초기화",(dialog,which)->{CookieManager.getInstance().removeAllCookies(null);CookieManager.getInstance().flush();WebStorage.getInstance().deleteAllData();toast("로그인 정보를 초기화했습니다.");}).show();return true;});menu.show();}
    private void savePage(){if(!LinkParser.valid(page)){toast("페이지를 먼저 열어 주세요.");return;}addSelected(page,page);}
    private String targetList(){String list=getIntent().getStringExtra("list");return list==null?"default":list;}
    private void navigate(){String url=MainActivity.browserUrl(address.getText().toString());if(!LinkParser.valid(url)){toast("http:// 또는 https:// 주소를 입력해 주세요.");return;}synchronized(candidates){candidates.clear();}updateMedia();address.clearFocus();((android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(address.getWindowToken(),0);page=url;web.loadUrl(url);}
    private void add(String url,String ref){if(!LinkParser.valid(url))return;synchronized(candidates){if(candidates.size()<100)candidates.putIfAbsent(url,ref);}runOnUiThread(()->{if(!isFinishing()&&!isDestroyed())updateMedia();});}
    private void collect(){collect(false);} private void collect(boolean show){if(web==null||isFinishing())return;String collectedPage=page;web.evaluateJavascript(COLLECT,value->{if(!collectedPage.equals(page)||isDestroyed())return;try{String decoded=(String)new JSONTokener(value).nextValue();JSONObject o=new JSONObject(decoded);JSONArray urls=o.getJSONArray("urls");for(int i=0;i<urls.length();i++)add(urls.optString(i),page);if(show)showMedia();}catch(Exception ignored){if(show)showMedia();}});}
    private void showMedia(){ArrayList<String> urls,refs;synchronized(candidates){urls=new ArrayList<>(candidates.keySet());refs=new ArrayList<>(candidates.values());}if(urls.isEmpty()){toast("영상 재생 후 다시 눌러 주세요. DRM 영상은 저장할 수 없습니다.");return;}String[] labels=new String[urls.size()];for(int i=0;i<urls.size();i++){String u=urls.get(i);String type=u.contains("m3u8")?"HLS 스트림":u.contains("mpd")?"DASH 스트림":"미디어 파일";try{labels[i]=type+" · "+LinkParser.host(u)+"\n"+new URI(u).getPath();}catch(Exception e){labels[i]=type;}}new AlertDialog.Builder(this).setTitle("저장할 미디어 선택").setItems(labels,(d,n)->addSelected(urls.get(n),refs.get(n))).setNegativeButton("닫기",null).show();}
    private void addSelected(String url,String ref){try{File dir=new File(getFilesDir(),"cookies");dir.mkdirs();File jar=new File(dir,UUID.randomUUID()+".txt");StringBuilder s=new StringBuilder("# Netscape HTTP Cookie File\n");LinkedHashSet<String> origins=new LinkedHashSet<>(Arrays.asList(url,ref));for(String origin:origins){if(!LinkParser.valid(origin))continue;String host=LinkParser.host(origin);String cookies=CookieManager.getInstance().getCookie(origin);if(cookies==null)continue;for(String part:cookies.split(";")){int eq=part.indexOf('=');if(eq<1)continue;String name=part.substring(0,eq).trim(),val=part.substring(eq+1).trim();if(name.matches(".*[\\r\\n\\t].*")||val.matches(".*[\\r\\n\\t].*"))continue;s.append(host).append("\tFALSE\t/\t").append(origin.startsWith("https")?"TRUE":"FALSE").append("\t0\t").append(name).append('\t').append(val).append('\n');}}try(FileOutputStream out=new FileOutputStream(jar)){out.write(s.toString().getBytes(StandardCharsets.UTF_8));}String title=web.getTitle()==null?LinkParser.host(url):web.getTitle();JSONObject result=Store.command(Store.obj("action","add","text",url,"title",title,"list",targetList(),"referer",ref,"cookieFile",jar.getAbsolutePath(),"userAgent",web.getSettings().getUserAgentString()));if(result.optInt("added")<1)jar.delete();toast(result.optInt("added")>0?"목록에 추가했습니다. 앱으로 돌아가 다운로드를 시작하세요.":"이미 목록에 있는 주소입니다.");}catch(Exception e){toast("미디어를 추가하지 못했습니다.");}}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    private int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
    private File cookieJar(String url,String ref)throws Exception{File dir=new File(getFilesDir(),"cookies");dir.mkdirs();File file=new File(dir,UUID.randomUUID()+".txt");StringBuilder s=new StringBuilder("# Netscape HTTP Cookie File\n");LinkedHashSet<String> urls=new LinkedHashSet<>(Arrays.asList(url,ref));for(String origin:urls){if(!LinkParser.valid(origin))continue;String cookies=CookieManager.getInstance().getCookie(origin);if(cookies==null)continue;for(String part:cookies.split(";")){int eq=part.indexOf('=');if(eq<1)continue;String key=part.substring(0,eq).trim(),val=part.substring(eq+1).trim();if(key.matches(".*[\\r\\n\\t].*")||val.matches(".*[\\r\\n\\t].*"))continue;s.append(LinkParser.host(origin)).append("\tFALSE\t/\t").append(origin.startsWith("https")?"TRUE":"FALSE").append("\t0\t").append(key).append('\t').append(val).append('\n');}}try(FileOutputStream out=new FileOutputStream(file)){out.write(s.toString().getBytes(StandardCharsets.UTF_8));}return file;}
    private void retryOriginal(){String id=getIntent().getStringExtra("taskId"),original=getIntent().getStringExtra("url");try{JSONObject t=id==null?null:Store.task(id);if(t!=null&&Arrays.asList("queued","analyzing","downloading","exporting","pausing","completed").contains(t.optString("status"))){toast("진행 중이거나 완료한 항목입니다.");return;}File jar=cookieJar(original,page);if(t!=null){Store.patch(id,Store.obj("cookieFile",jar.getAbsolutePath(),"referer",page,"userAgent",web.getSettings().getUserAgentString()));Store.command(Store.obj("action","enqueue","id",id));startForegroundService(new android.content.Intent(this,DownloadService.class));toast("로그인 정보로 원래 주소를 재시도합니다.");finish();}else{JSONObject r=Store.command(Store.obj("action","add","text",original,"list",targetList(),"cookieFile",jar.getAbsolutePath(),"referer",page,"userAgent",web.getSettings().getUserAgentString()));if(r.optInt("added")==0)jar.delete();toast("목록에서 다운로드를 시작해 주세요.");}}catch(Exception e){toast("재시도를 준비하지 못했습니다.");}}
    @Override protected void onSaveInstanceState(Bundle state){super.onSaveInstanceState(state);if(web!=null)web.saveState(state);}
    @Override protected void onPause(){super.onPause();timer.removeCallbacks(poll);if(web!=null)web.onPause();}
    @Override protected void onResume(){super.onResume();if(web!=null){web.onResume();timer.removeCallbacks(poll);timer.postDelayed(poll,1800);}}
    @Override public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();}
    @Override protected void onDestroy(){timer.removeCallbacksAndMessages(null);if(web!=null){web.stopLoading();web.destroy();web=null;}super.onDestroy();}
}
